version: '3.8'

services:
  php:
    container_name: php
    build:
      context: .
    env_file: .env
    volumes:
      - ./:/var/www/html/lar-react-crud
    networks:
      - app-network

  web:
    container_name: web
    image: nginx:1.17
    working_dir: /var/www/html/lar-react-crud
    volumes:
      - ./:/var/www/html/lar-react-crud
      - .docker/nginx/nginx_template_local.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8001:80"
    networks:
      - app-network

  mysql:
    container_name: mysql
    image: mysql:5.7
    # restart: unless-stopped
    # tty: true
    # ports:
    #   - "3309:3306"
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_ROOT_HOST: "%"
      MYSQL_ROOT_PASSWORD: "${DB_PASSWORD}"
      MYSQL_DATABASE: "${DB_DATABASE}"
      MYSQL_USER: "${DB_USERNAME}"
      MYSQL_PASSWORD: "${DB_PASSWORD}"
    volumes:
      - mysqldata:/var/lib/mysql
    ports:
      - "33060:3306"
    networks:
      - app-network

  # db2:
  #   container_name: db2
  #   image: mysql:5.7
  #   environment:
  #     MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
  #     MYSQL_ROOT_HOST: "%"
  #     MYSQL_ROOT_PASSWORD: "${DB_PASSWORD2}"
  #     MYSQL_DATABASE: "${DB_DATABASE2}"
  #     MYSQL_USER: "${DB_USERNAME2}"
  #     MYSQL_PASSWORD: "${DB_PASSWORD2}"
  #   volumes:
  #     - mysqldata2:/var/lib/mysql2
  #   networks:
  #     - app-network

volumes:
  mysqldata:
  # mysqldata2:

networks:
  app-network:
    driver: bridge